except ImportError
Running python 3.7 this throws an ImportError (which is a superclass of ModuleNotFoundError)

ImportError: cannot import name 'ProxyCrawlMiddleware' from 'proxycrawl' (XXX/lib/python3.7/site-packages/proxycrawl/__init__.py)

Catching ImportError successfully makes us import from ".proxycrawl" on python 3